version: "3.9"

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: "exit 0"
    ports:
      - 5432:5432
    networks:
      - app_network

  back:
    build:
      context: ./back
    volumes:
      - ./back:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./back/.env
    command: ["npm", "run", "start"]
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
